version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-4
    environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    volumes:
    - /opt/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    build: ./
    image: sameersbn/redmine:4.1.1-8
    depends_on:
    - postgresql
    environment:
    - TZ=Europe/Prague

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.gmail.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=redminetrebestovice@gmail.com
    - SMTP_PASS=RedHeslo12345
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=true
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=redminetrebestovice@gmail.com
    - IMAP_PASS=RedHeslo12345
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "8050:80"
    volumes:
    - /opt/docker/redmine/redmine:/home/redmine/data
    - /opt/docker/redmine/redmine-logs:/var/log/redmine
