version: '3.3'

services:
   wordpress:
      image: wordpress:latest
      ports:
         - "8001:80"
      restart: always
      environment:
         WORDPRESS_DB_HOST: MySQL-shared:3306
         WORDPRESS_DB_USER: ${MYSQL_USER}
         WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
         WORDPRESS_DB_NAME: pencakova
         DOCKER_COMPOSE_YML_LOCATION: ${PWD}
      volumes:
         - ./wp-content:/var/www/html/wp-content
      container_name: pencakova_wp

